export interface Badge {
  name: string;
  badgeId: string;
  category: string;
  requirement: string;
  tagline: string;
  image?: string;
}

export interface RankSection {
  rank: string;
  subtitle: string;
  color: string;
  glowColor: string;
  borderColor: string;
  ledColor: string;
  badges: Badge[];
}

export const ranks: RankSection[] = [
  {
    rank: "E-Rank",
    subtitle: "The Awakening",
    color: "text-gray-300",
    glowColor: "",
    borderColor: "border-gray-300/30",
    ledColor: "rgba(209,213,219,0.8)",
    badges: [
      {
        name: "Awakened",
        badgeId: "streak_e",
        category: "Streak",
        requirement: "3-day streak",
        tagline: "The system has noticed you",
        image: "/badges/E-Rank-Awakened.png",
      },
      {
        name: "First Blood",
        badgeId: "tasks_e",
        category: "Tasks",
        requirement: "10 tasks completed",
        tagline: "Your first shadows rise",
        image: "/badges/E-Rank-First-Blood.png",
      },
      {
        name: "Gate Finder",
        badgeId: "goals_e",
        category: "Goals",
        requirement: "Complete 1 goal",
        tagline: "Your first gate cleared",
        image: "/badges/E-Rank-Gate-Finder.png",
      },
      {
        name: "Dawn Waker",
        badgeId: "early_bird_e",
        category: "Early Bird",
        requirement: "5 tasks before 7 AM",
        tagline: "The early hunter catches prey",
        image: "/badges/E-Rank-Dawn-Waker.png",
      },
      {
        name: "Night Walker",
        badgeId: "night_owl_e",
        category: "Night Owl",
        requirement: "5 tasks after 10 PM",
        tagline: "Shadows welcome you",
        image: "/badges/E-Rank-Night-Walker.png",
      },
      {
        name: "Second Chance",
        badgeId: "comeback_e",
        category: "Comeback",
        requirement: "Return after 3 days inactive",
        tagline: "You came back",
        image: "/badges/E-Rank-Second-Chance.png",
      },
      {
        name: "Clean Sweep",
        badgeId: "perfect_day_e",
        category: "Perfect Day",
        requirement: "3 perfect days",
        tagline: "No task left behind",
        image: "/badges/E-Rank-Clean-Sweep.png",
      },
      {
        name: "Quick Start",
        badgeId: "speed_e",
        category: "Speed",
        requirement: "5 instant completions",
        tagline: "No hesitation",
        image: "/badges/E-Rank-Quick-Start.png",
      },
    ],
  },
  {
    rank: "D-Rank",
    subtitle: "The Grind Begins",
    color: "text-green-300",
    glowColor: "shadow-[0_0_10px_rgba(74,222,128,0.3)]",
    borderColor: "border-green-300/30",
    ledColor: "rgba(74,222,128,0.8)",
    badges: [
      {
        name: "Persistent",
        badgeId: "streak_d",
        category: "Streak",
        requirement: "7-day streak",
        tagline: "A week of discipline",
        image: "/badges/D-Rank-Persistent.png",
      },
      {
        name: "Squad Leader",
        badgeId: "tasks_d",
        category: "Tasks",
        requirement: "50 tasks completed",
        tagline: "A small army forms",
        image: "/badges/D-Rank-Squad-Leader.png",
      },
      {
        name: "Gate Raider",
        badgeId: "goals_d",
        category: "Goals",
        requirement: "Complete 5 goals",
        tagline: "You hunt for challenges",
        image: "/badges/D-Rank-Gate-Raider.png",
      },
      {
        name: "Morning Strike",
        badgeId: "early_bird_d",
        category: "Early Bird",
        requirement: "20 tasks before 7 AM",
        tagline: "Discipline starts at sunrise",
        image: "/badges/D-Rank-Morning-Strike.png",
      },
      {
        name: "Dusk Hunter",
        badgeId: "night_owl_d",
        category: "Night Owl",
        requirement: "20 tasks after 10 PM",
        tagline: "You thrive in darkness",
        image: "/badges/D-Rank-Dusk-Hunter.png",
      },
      {
        name: "Resilient",
        badgeId: "comeback_d",
        category: "Comeback",
        requirement: "Return after 7 days inactive",
        tagline: "Setbacks don't define you",
        image: "/badges/D-Rank-Resilient.png",
      },
      {
        name: "Full Clear",
        badgeId: "perfect_day_d",
        category: "Perfect Day",
        requirement: "10 perfect days",
        tagline: "You clear every dungeon",
        image: "/badges/D-Rank-Full-Clear.png",
      },
      {
        name: "Rapid Fire",
        badgeId: "speed_d",
        category: "Speed",
        requirement: "20 instant completions",
        tagline: "Think, act, done",
        image: "/badges/D-Rank-Rapid-Fire.png",
      },
    ],
  },
  {
    rank: "C-Rank",
    subtitle: "Rising Hunter",
    color: "text-blue-400",
    glowColor: "shadow-[0_0_10px_rgba(0,163,255,0.2)]",
    borderColor: "border-blue-400/30",
    ledColor: "rgba(96,165,250,0.8)",
    badges: [
      {
        name: "Relentless",
        badgeId: "streak_c",
        category: "Streak",
        requirement: "14-day streak",
        tagline: "You don't know how to quit",
        image: "/badges/C-Rank-Relentless.png",
      },
      {
        name: "Platoon Commander",
        badgeId: "tasks_c",
        category: "Tasks",
        requirement: "150 tasks completed",
        tagline: "They march at your command",
        image: "/badges/C-Rank-Platoon-Commander.png",
      },
      {
        name: "Gate Breaker",
        badgeId: "goals_c",
        category: "Goals",
        requirement: "Complete 15 goals",
        tagline: "No gate can hold you",
        image: "/badges/C-Rank-Gate-Breaker.png",
      },
      {
        name: "First Light",
        badgeId: "early_bird_c",
        category: "Early Bird",
        requirement: "50 tasks before 7 AM",
        tagline: "You own the morning",
        image: "/badges/C-Rank-First-Light.png",
      },
      {
        name: "Midnight Striker",
        badgeId: "night_owl_c",
        category: "Night Owl",
        requirement: "50 tasks after 10 PM",
        tagline: "The night fuels you",
        image: "/badges/C-Rank-Midnight-Striker.png",
      },
      {
        name: "Reborn",
        badgeId: "comeback_c",
        category: "Comeback",
        requirement: "Return after 14 days inactive",
        tagline: "A new awakening",
        image: "/badges/C-Rank-Reborn.png",
      },
      {
        name: "Zero Escape",
        badgeId: "perfect_day_c",
        category: "Perfect Day",
        requirement: "25 perfect days",
        tagline: "Nothing escapes your grasp",
        image: "/badges/C-Rank-Zero-Escape.png",
      },
      {
        name: "Blitz",
        badgeId: "speed_c",
        category: "Speed",
        requirement: "50 instant completions",
        tagline: "Speed is your weapon",
        image: "/badges/C-Rank-Blitz.png",
      },
    ],
  },
  {
    rank: "B-Rank",
    subtitle: "Elite Hunter",
    color: "text-purple-400",
    glowColor: "shadow-[0_0_10px_rgba(123,44,191,0.3)]",
    borderColor: "border-purple-400/30",
    ledColor: "rgba(192,132,252,0.8)",
    badges: [
      {
        name: "Unstoppable",
        badgeId: "streak_b",
        category: "Streak",
        requirement: "30-day streak",
        tagline: "A month of dominance",
        image: "/badges/B-Rank-Unstoppable.png",
      },
      {
        name: "Legion General",
        badgeId: "tasks_b",
        category: "Tasks",
        requirement: "500 tasks completed",
        tagline: "An army awaits your orders",
        image: "/badges/B-Rank-Legion-General.png",
      },
      {
        name: "Dungeon Master",
        badgeId: "goals_b",
        category: "Goals",
        requirement: "Complete 30 goals",
        tagline: "Dungeons fear your name",
        image: "/badges/B-Rank-Dungeon-Master.png",
      },
      {
        name: "Sunrise Hunter",
        badgeId: "early_bird_b",
        category: "Early Bird",
        requirement: "100 tasks before 7 AM",
        tagline: "Dawn is your domain",
        image: "/badges/B-Rank-Sunrise-Hunter.png",
      },
      {
        name: "Shadow Stalker",
        badgeId: "night_owl_b",
        category: "Night Owl",
        requirement: "100 tasks after 10 PM",
        tagline: "Darkness is your weapon",
        image: "/badges/B-Rank-Shadow-Stalker.png",
      },
      {
        name: "Phoenix",
        badgeId: "comeback_b",
        category: "Comeback",
        requirement: "Return after 30 days inactive",
        tagline: "From ashes, you rise",
        image: "/badges/B-Rank-Phoenix.png",
      },
      {
        name: "Absolute",
        badgeId: "perfect_day_b",
        category: "Perfect Day",
        requirement: "50 perfect days",
        tagline: "Perfection is habit",
        image: "/badges/B-Rank-Absolute.png",
      },
      {
        name: "Lightning",
        badgeId: "speed_b",
        category: "Speed",
        requirement: "100 instant completions",
        tagline: "Faster than thought",
        image: "/badges/B-Rank-Lightning.png",
      },
    ],
  },
  {
    rank: "A-Rank",
    subtitle: "National Level",
    color: "text-orange-300",
    glowColor: "shadow-[0_0_10px_rgba(251,146,60,0.3)]",
    borderColor: "border-orange-300/30",
    ledColor: "rgba(253,186,116,0.8)",
    badges: [
      {
        name: "Unbreakable",
        badgeId: "streak_a",
        category: "Streak",
        requirement: "90-day streak",
        tagline: "Nothing can shatter your will",
        image: "/badges/A-Rank-Unbreakable.png",
      },
      {
        name: "Shadow Marshal",
        badgeId: "tasks_a",
        category: "Tasks",
        requirement: "1,500 tasks completed",
        tagline: "Thousands rise for you",
        image: "/badges/A-Rank-Shadow-Marshal.png",
      },
      {
        name: "Rift Walker",
        badgeId: "goals_a",
        category: "Goals",
        requirement: "Complete 60 goals",
        tagline: "You walk between worlds",
        image: "/badges/A-Rank-Rift-Walker.png",
      },
      {
        name: "Aurora Knight",
        badgeId: "early_bird_a",
        category: "Early Bird",
        requirement: "250 tasks before 7 AM",
        tagline: "Light follows your lead",
        image: "/badges/A-Rank-Aurora-Knight.png",
      },
      {
        name: "Void Knight",
        badgeId: "night_owl_a",
        category: "Night Owl",
        requirement: "250 tasks after 10 PM",
        tagline: "You rule the silent hours",
        image: "/badges/A-Rank-Void-Knight.png",
      },
      {
        name: "Undying",
        badgeId: "comeback_a",
        category: "Comeback",
        requirement: "Return after 60 days inactive",
        tagline: "Death cannot hold you",
        image: "/badges/A-Rank-Undying.png",
      },
      {
        name: "Flawless",
        badgeId: "perfect_day_a",
        category: "Perfect Day",
        requirement: "100 perfect days",
        tagline: "Error is not in your code",
        image: "/badges/A-Rank-Flawless.png",
      },
      {
        name: "Flash Step",
        badgeId: "speed_a",
        category: "Speed",
        requirement: "250 instant completions",
        tagline: "You move like shadow",
        image: "/badges/A-Rank-Flash-Step.png",
      },
    ],
  },
  {
    rank: "S-Rank",
    subtitle: "Monarch Level",
    color: "text-red-400",
    glowColor: "shadow-[0_0_15px_rgba(230,57,70,0.4)]",
    borderColor: "border-red-400/30",
    ledColor: "rgba(248,113,113,0.8)",
    badges: [
      {
        name: "Immortal",
        badgeId: "streak_s",
        category: "Streak",
        requirement: "365-day streak",
        tagline: "Time bends to your discipline",
        image: "/badges/S-Rank-Immortal.png",
      },
      {
        name: "Monarch's Army",
        badgeId: "tasks_s",
        category: "Tasks",
        requirement: "5,000 tasks completed",
        tagline: "Infinite shadows, one ruler",
        image: "/badges/S-Rank-Monarchs-Army.png",
      },
      {
        name: "Gate Sovereign",
        badgeId: "goals_s",
        category: "Goals",
        requirement: "Complete 100 goals",
        tagline: "All gates bow to you",
        image: "/badges/S-Rank-Gate-Sovereign.png",
      },
      {
        name: "Sun Sovereign",
        badgeId: "early_bird_s",
        category: "Early Bird",
        requirement: "500 tasks before 7 AM",
        tagline: "The sun rises for you",
        image: "/badges/S-Rank-Sun-Sovereign.png",
      },
      {
        name: "Night Monarch",
        badgeId: "night_owl_s",
        category: "Night Owl",
        requirement: "500 tasks after 10 PM",
        tagline: "The night belongs to you",
        image: "/badges/S-Rank-Night-Monarch.png",
      },
      {
        name: "Eternal Return",
        badgeId: "comeback_s",
        category: "Comeback",
        requirement: "Return after 90+ days inactive",
        tagline: "Legends never truly fall",
        image: "/badges/S-Rank-Eternal-Return.png",
      },
      {
        name: "Perfect Monarch",
        badgeId: "perfect_day_s",
        category: "Perfect Day",
        requirement: "250 perfect days",
        tagline: "Perfection incarnate",
        image: "/badges/S-Rank-Perfect-Monarch.png",
      },
      {
        name: "Time Bender",
        badgeId: "speed_s",
        category: "Speed",
        requirement: "500 instant completions",
        tagline: "Time obeys your will",
        image: "/badges/S-Rank-Time-Bender.png",
      },
    ],
  },
];

// Map badge IDs to badge names for toast notifications
export const badgeIdToName: Record<string, string> = Object.fromEntries(
  ranks.flatMap((section) =>
    section.badges.map((badge) => [badge.badgeId, badge.name])
  )
);

export const categoryIcons: Record<string, string> = {
  Streak: "🔥",
  Tasks: "⚔️",
  Goals: "🏁",
  "Early Bird": "🌅",
  "Night Owl": "🌙",
  Comeback: "💀",
  "Perfect Day": "✨",
  Speed: "⚡",
};
