ACHIEVEMENT_THRESHOLDS = {
    "Streak": [
        {"badge_id": "streak_e", "threshold": 3},
        {"badge_id": "streak_d", "threshold": 7},
        {"badge_id": "streak_c", "threshold": 14},
        {"badge_id": "streak_b", "threshold": 30},
        {"badge_id": "streak_a", "threshold": 90},
        {"badge_id": "streak_s", "threshold": 365},
    ],
    "Tasks": [
        {"badge_id": "tasks_e", "threshold": 10},
        {"badge_id": "tasks_d", "threshold": 50},
        {"badge_id": "tasks_c", "threshold": 150},
        {"badge_id": "tasks_b", "threshold": 500},
        {"badge_id": "tasks_a", "threshold": 1500},
        {"badge_id": "tasks_s", "threshold": 5000},
    ],
    "Goals": [
        {"badge_id": "goals_e", "threshold": 1},
        {"badge_id": "goals_d", "threshold": 5},
        {"badge_id": "goals_c", "threshold": 15},
        {"badge_id": "goals_b", "threshold": 30},
        {"badge_id": "goals_a", "threshold": 60},
        {"badge_id": "goals_s", "threshold": 100},
    ],
    "Early Bird": [
        {"badge_id": "early_bird_e", "threshold": 5},
        {"badge_id": "early_bird_d", "threshold": 20},
        {"badge_id": "early_bird_c", "threshold": 50},
        {"badge_id": "early_bird_b", "threshold": 100},
        {"badge_id": "early_bird_a", "threshold": 250},
        {"badge_id": "early_bird_s", "threshold": 500},
    ],
    "Night Owl": [
        {"badge_id": "night_owl_e", "threshold": 5},
        {"badge_id": "night_owl_d", "threshold": 20},
        {"badge_id": "night_owl_c", "threshold": 50},
        {"badge_id": "night_owl_b", "threshold": 100},
        {"badge_id": "night_owl_a", "threshold": 250},
        {"badge_id": "night_owl_s", "threshold": 500},
    ],
    "Comeback": [
        {"badge_id": "comeback_e", "threshold": 3},
        {"badge_id": "comeback_d", "threshold": 7},
        {"badge_id": "comeback_c", "threshold": 14},
        {"badge_id": "comeback_b", "threshold": 30},
        {"badge_id": "comeback_a", "threshold": 60},
        {"badge_id": "comeback_s", "threshold": 90},
    ],
    "Perfect Day": [
        {"badge_id": "perfect_day_e", "threshold": 3},
        {"badge_id": "perfect_day_d", "threshold": 10},
        {"badge_id": "perfect_day_c", "threshold": 25},
        {"badge_id": "perfect_day_b", "threshold": 50},
        {"badge_id": "perfect_day_a", "threshold": 100},
        {"badge_id": "perfect_day_s", "threshold": 250},
    ],
    "Speed": [
        {"badge_id": "speed_e", "threshold": 5},
        {"badge_id": "speed_d", "threshold": 20},
        {"badge_id": "speed_c", "threshold": 50},
        {"badge_id": "speed_b", "threshold": 100},
        {"badge_id": "speed_a", "threshold": 250},
        {"badge_id": "speed_s", "threshold": 500},
    ],
}

CATEGORY_TO_STAT_FIELD = {
    "Streak": "longest_streak",
    "Tasks": "total_tasks_completed",
    "Goals": "total_goals_completed",
    "Early Bird": "early_bird_count",
    "Night Owl": "night_owl_count",
    "Comeback": "longest_inactive_days",
    "Perfect Day": "perfect_days",
    "Speed": "instant_completions",
}
